#cloud-config
users:
  - default
  - name: opsuser01
    sudo: False
    lock_passwd: True
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC0XylQD379AYnTxGG0eJ83mAUVF6HQn6NLvTGYgunKtLcDtB0UwP2vL3p3vUh+r1KUvMvHzA5wo8No3NktEy0pYPQFr/gmKpSTAN4tuqeVt7Yv9iflNiO1jV+iGVNKge2Y2UcaS4m0RYPpRXldV9CEgX1zzLu8IVcb5c/xLf/cnutighDjeG+6/CPEE69R3NAzh7w9dkU1exfOg1eVTeQT6+t2MscLn3zYgiGP13zp6lGN6N06V+n9x+OAmvoYWcm3U82v5XoSvhvVdFjGgTo1E07l13IS/ktjUSXh284ufwTn/B7zLRsDbo83TBxodGK3LB4G3meHNGZyEVG/x6Y9Cni86GVYMSdPqGTP0JR3tydFdXCPpxvUdZUw9YjrdEysE8AsYvJtHX7aNHrLXxOK7V5PqPZJuTJBd+wf4VpamOlm2D/ta6YLNP7YchrOMSKgpdZp7oCiX4V23DnnT0AbSovKplsU0sSUR2qAtYb6fKl5ULAM2frHe/cSIbI+WIM/F9QIplSLUMZZP9PeHhFAMaFvfEEF+VVbOmySdzKkMgsmE07djgMNkvIxd7zpEQNzAf+ZjHGRyqkwMyYZVNhNudG2M1S/3i0TAMUnFyjigltHQsV+L+6QOm2nHZvXRoEkOOBCTlUKbnAhJ9AiqrRPyGHjEYftBNPVy2DPlHiRkw== saurabh_vartak@cc-4899daa7-7cd54c4b9f-s7vfk
